-- MySQL Script generated by MySQL Workbench
-- Tue Mar 13 11:34:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema budgetplanner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema budgetplanner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `budgetplanner` DEFAULT CHARACTER SET utf8 ;
USE `budgetplanner` ;

-- -----------------------------------------------------
-- Table `budgetplanner`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `budgetplanner`.`Account`;
CREATE TABLE IF NOT EXISTS `budgetplanner`.`Account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(24) NULL,
  `IBAN` VARCHAR(34) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budgetplanner`.`Label`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `budgetplanner`.`Label`;
CREATE TABLE IF NOT EXISTS `budgetplanner`.`Label` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budgetplanner`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `budgetplanner`.`Payment`;
CREATE TABLE IF NOT EXISTS `budgetplanner`.`Payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `amount` FLOAT NULL,
  `currency` VARCHAR(45) NULL,
  `detail` VARCHAR(255) NULL,
  `accountId` INT NOT NULL,
  `counterAccountId` INT NOT NULL,
  `labelId` INT,
  PRIMARY KEY (`id`, `accountId`, `counterAccountId`, `labelId`),
  INDEX `fk_Payment_Account_idx` (`accountId` ASC),
  INDEX `fk_Payment_Counter_Account_idx` (`counterAccountId` ASC),
  INDEX `fk_Payment_Label_idx` (`labelId` ASC),
  CONSTRAINT `fk_Payment_Account_Id`
    FOREIGN KEY (`accountId`)
    REFERENCES `budgetplanner`.`Account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Payment_CounterAccount_Id`
    FOREIGN KEY (`counterAccountId`)
    REFERENCES `budgetplanner`.`Account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
